services:
  - type: web
    name: camille-guide
    runtime: python
    plan: free
    healthCheckPath: /
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: FLASK_ENV
        value: production
